package de.uniba.kinf.projm.hylleblomst.keys;

/**
 * @author Christian, Johannes
 *
 */
public enum SearchFieldKeys {

	ANREDE, TITEL, VORNAME, NACHNAME, ADLIG, JESUIT, WIRTSCHAFTSLAGE, ORT, FACH, FAKULTAETEN, SEMINAR, GRADUIERT, STUDIENJAHR_VON, STUDIENJAHR_BIS, EINSCHREIBEDATUM_VON, EINSCHREIBEDATUM_BIS, ZUSAETZE, FUNDORTE, ANMERKUNGEN, NUMMER, SEITE_ORIGINALE, NUMMER_HESS;
}
