package de.uniba.kinf.projm.hylleblomst.logic;

public enum ColumnKeys {

	ANREDE, ANREDE_NORM,
	TITEL, TITEL_NORM,
	VORNAME_NORM, 
	NACHNAME, NACHNAME_NORM, 
	ADELIG, JESUIT,
	WIRTSCHAFTL_LAGE, WIRTSCHAFTL_LAGE_NORM, 
	ORT, ORT_NORM, ORT_ABWEICHUNG, 
	STUDIENFACH, STUDIENFACH_NORM, 
	FAKULTAET,
	SEMINAR, SEMINAR_NORM, 
	GRADUIERT,
	STUDIENJAHR, STUDJAHR_VON, STUDJAHR_BIS,
	EINSCHREIBEDATUM_TAG, EINSCHREIBEDATUM_MONAT, EINSCHREIBEDATUM_JAHR,
	ZUSAETZE, 
	FUNDORT,
	ANMERKUNGEN,
	NUMMER,
	SEITE_ORIGINAL,
	NUMMER_HESS;
}
