package de.uniba.kinf.projm.hylleblomst.logic;

public enum ColumnKeys {

	ANREDE, ANREDE_NORM,
	TITEL, TITEL_NORM,
	VORNAME_NORM, // VORNAMEN TRAD
	NACHNAME, NACHNAME_NORM, // NACHNAME TRAD
	ADELIG, JESUIT,
	WIRTSCHAFTL_LAGE, WIRTSCHAFTL_LAGE_NORM, // WIRTSCHAFTL_LAGE_TRAD
	ORT, ORT_NORM, ORT_ABWEICHUNG, // ORT_TRAD
	STUDIENFACH, STUDIENFACH_NORM, // STUDIENFACH_TRAD
	FAKULTAET,
	SEMINAR, SEMINAR_NORM, // SEMINAR_TRAD
	GRADUIERT,
	STUDIENJAHR, STUDJAHR_VON, STUDJAHR_BIS,
	EINSCHREIBEDATUM_TAG, EINSCHREIBEDATUM_MONAT, EINSCHREIBEDATUM_JAHR,
	ZUSAETZE, // ZUSAETZE_TRAD
	FUNDORT,
	ANMERKUNGEN,
	NUMMER,
	SEITE_ORIGINAL,
	NUMMER_HESS;
}
