package de.uniba.kinf.projm.hylleblomst.logic;

public enum SearchFieldKeys {

	ANREDE_TRAD, ANREDE_NORM, TITEL_TRAD, TITEL_NORM, VORNAME_NORM, VORNAME_TRAD, NACHNAME_TRAD, NACHNAME_NORM, ADELIG, JESUIT, WIRTSCHAFTSLAGE_TRAD, WIRTSCHAFTSLAGE_NORM, ORT_TRAD, ORT_NORM, ORT_ABWEICHUNG_NORM, FACH_TRAD, FACH_NORM, FAKULTAETEN, SEMINAR_TRAD, SEMINAR_NORM, GRADUIERT, STUDIENJAHR, EINSCHREIBEDATUM, ZUSAETZE, FUNDORTE, ANMERKUNGEN, NUMMER, SEITE_ORIGINALE, NUMMER_HESS;
}
