package de.uniba.kinf.projm.hylleblomst.logic;

public enum SearchFieldKeys {

	ANREDE, TITEL, VORNAME, NACHNAME, ADLIG, JESUIT, WIRTSCHAFTSLAGE, ORT, FACH, FAKULTAETEN, SEMINAR, GRADUIERT, STUDIENJAHR, EINSCHREIBEDATUM, ZUSAETZE, FUNDORTE, ANMERKUNGEN, NUMMER, SEITE_ORIGINALE, NUMMER_HESS;
}
