CREATE SCHEMA SQL_UTIL

CREATE FUNCTION SQL_UTIL.TO_DEGREES
( RADIANS DOUBLE )
RETURNS DOUBLE
PARAMETER STYLE JAVA
NO SQL LANGUAGE JAVA
EXTERNAL NAME 'java.lang.Math.toDegrees'

CREATE FUNCTION function-name ( [ FunctionParameter 
   [, FunctionParameter] ] * ) RETURNS ReturnDataType [ FunctionElement ] *
   
   
CREATE FUNCTION SQL_UTIL.GROUP_CONCAT 
	( SEPARATOR CHAR, ARGS VARCHAR(255) ... )
	RETURNS VARCHAR(2000)
	PARAMETER STYLE DERBY
	NO SQL LANGUAGE JAVA
	EXTERNAL NAME 'de.uniba.kinf.projm.hylleblomst.database.sql.utils.GroupConcat.groupConcat'
	
DROP FUNCTION SQL_UTIL.GROUP_CONCAT

SELECT SQL_UTIL.GROUP_CONCAT(',', 'Eins', 'Zwei') FROM HYLLEBLOMST.ANREDE_NORM