CREATE SCHEMA SQL_UTIL

CREATE FUNCTION SQL_UTIL.TO_DEGREES
( RADIANS DOUBLE )
RETURNS DOUBLE
PARAMETER STYLE JAVA
NO SQL LANGUAGE JAVA
EXTERNAL NAME 'java.lang.Math.toDegrees'

SELECT SQL_UTIL.TO_DEGREES (10.0) FROM Hylleblomst.Anrede_Norm   
   
CREATE FUNCTION SQL_UTIL.GROUP_CONCAT 
	( SEPARATOR CHAR, ARGS VARCHAR(255) ... )
	RETURNS VARCHAR(2000)
	PARAMETER STYLE DERBY
	NO SQL LANGUAGE JAVA
	EXTERNAL NAME 'de.uniba.kinf.projm.hylleblomst.database.sql.utils.GroupConcat.groupConcat'
	
CREATE procedure SQL_UTIL.GROUP_CONCAT(
	OUT CONCATENATION VARCHAR(255),
	IN SEPARATOR CHAR,
	IN ARGS VARCHAR(255) ... 
	)
	PARAMETER STYLE DERBY
	LANGUAGE JAVA
	DYNAMIC RESULT SETS 0
	EXTERNAL NAME 'de.uniba.kinf.projm.hylleblomst.database.sql.utils.GroupConcat.groupConcat'

	
DROP procedure SQL_UTIL.GROUP_CONCAT

CALL SQLJ.INSTALL_JAR (
	'C:/Users/Simon/git/KInf-Projekt/lib/groupConcat.jar','SQL_UTIL.groupConcat',0)
CALL SQLJ.REMOVE_JAR (
	'SQL_UTIL.groupConcat.jar',0)
	
CALL SQL_UTIL.GROUP_CONCAT(',',?, 'Eins', 'Zwei')





