DROP TABLE HYLLEBLOMST.zusaetze_info;
DROP TABLE hylleblomst.zusaetze;	
DROP TABLE hylleblomst.wirtschaftslage_info;
DROP TABLE hylleblomst.wirtschaftslage_trad;
DROP TABLE hylleblomst.titel_trad;
DROP TABLE hylleblomst.seminar_info;
DROP TABLE hylleblomst.seminar_trad;
DROP TABLE hylleblomst.ort_info;
DROP TABLE hylleblomst.ort_trad;
DROP TABLE hylleblomst.ort_norm;
DROP TABLE hylleblomst.vorname_info;
DROP TABLE hylleblomst.name_info;
DROP TABLE hylleblomst.vorname_trad;
DROP TABLE hylleblomst.name_trad;
DROP TABLE hylleblomst.fach_info;
DROP TABLE hylleblomst.fach_trad;	
DROP TABLE hylleblomst.person;
DROP TABLE hylleblomst.anrede_trad;

DROP TABLE hylleblomst.anrede_norm;
DROP TABLE hylleblomst.fach_norm;
DROP TABLE hylleblomst.fakultaeten;
DROP TABLE hylleblomst.fundorte;
DROP TABLE hylleblomst.name_norm;
DROP TABLE hylleblomst.vorname_norm;
DROP TABLE hylleblomst.ort_abweichung_norm;
DROP TABLE hylleblomst.quellen;
DROP TABLE hylleblomst.seminar_norm;
DROP TABLE hylleblomst.titel_norm;
DROP TABLE hylleblomst.wirtschaftslage_norm;

DROP SCHEMA hylleblomst RESTRICT;